export const initialColors = [
  { hex: '#FF6B6B', name: 'Coral Red' },
  { hex: '#4ECDC4', name: 'Medium Turquoise' },
  { hex: '#45B7D1', name: 'Sky Blue' },
  { hex: '#96CEB4', name: 'Sage Green' },
  { hex: '#FFEEAD', name: 'Pale Yellow' },
  { hex: '#D4A5A5', name: 'Dusty Rose' },
  { hex: '#9B59B6', name: 'Purple' },
  { hex: '#3498DB', name: 'Blue' },
  { hex: '#1ABC9C', name: 'Turquoise' },
  { hex: '#2ECC71', name: 'Emerald' },
  { hex: '#F1C40F', name: 'Yellow' },
  { hex: '#E67E22', name: 'Orange' },
  { hex: '#F2F2F7', name: 'Light Gray' },
  { hex: '#007AFF', name: 'iOS Blue' },
  { hex: '#8E8E93', name: 'Gray' },
  { hex: '#FFFFFF', name: 'White' },
  { hex: '#D1D1D6', name: 'Silver' },
  { hex: '#4CD964', name: 'Green' },
  { hex: '#FF3B30', name: 'Red' },
  { hex: '#1c1c1e', name: 'Dark' },
  { hex: '#34C759', name: 'iOS Success' },
  { hex: '#FF9500', name: 'iOS Warning' },
  { hex: '#FF2D55', name: 'iOS Error' },
  { hex: '#5856D6', name: 'iOS Purple' },
  { hex: '#FF3B30', name: 'iOS Destructive' },
  { hex: '#30B0C7', name: 'iOS Tint' },
  { hex: '#64D2FF', name: 'iOS Light Blue' },
  { hex: '#98989D', name: 'iOS Secondary' },
];